name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a582a77ddb8b78bafde028b442d1f83b43ce0657bc1f789f20d2db80a3a67fc7"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
