name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27098841edd99925ad5e51c978aee66bf3ce726ac786f425a9ccd1f2b2da231d"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
