name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ac3b00f047e8f3f82e35dfa05669ed64414c6b8be8eb06ccda01bb150efb814"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
