name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b86aafb2e3f16dca6540fd98febf68058753a3debae458fb0f7449c549e2a000"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
