name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb6d584acc1bbe5aaa3b836e60046144e0b3c61b5efa734485c9d108c53347f0"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
