name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ebde311e353acc377fae1d2e5c97ac8ecb0f99bc5f61f40f9fb2d9e9a69ec2a"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
