name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11faf58cff08f95ba7dffb5ff30f1157dc04ef2a2479f792cc79ab09d7eb799e"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
