name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe7ceb71d6ae2bb0d441ec8cb18ed3ae803587d8d78768249b7ca600ad22437"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
