name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7f734a5c7d34431592f4bcb14e507f45e9829e6a6658f4867118f037b0fc61e"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
