name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d4998d299e8b06a657cacc008e989d8b0c0cb96c7fa34b2d95d0e03bfe335e7"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
