name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28eb23079ae3b8f7cf63fec2016dbb01f56c296ece07a7b0ae9ec9078e3bb28f"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
