name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bd57d7aaaf28b0ab9c4473c786d2bc12dbab6c6e3405904766f85a2b7b6ac09"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
