name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "421bf0f50d8f4379fb86a435e5d22b2c6a0eb8db9f156bced241341e146d3328"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
