name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70b1b4e4b300732041e3cfefe97d04c4d1b552bb330773699275839a8a09a449"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
