name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9aab9c66fd90276e8d6581c23548c791112f4bde7a78a1a44db892d35546f49"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
