name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dece3b06f0d2a9bed2d3d8d1482806181432e5760bf0e4d2c23646bff52a84b5"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
