name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40824612f9864ac31aa2c5d106ec88e9e93ff8d9e4597d7dfa55425659089f6c"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
