name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c7a01a804ade3d0fc0e488aa409165a120a57218a7418d1bd3560d64b87179"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
