name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abc5765e5e798c05bad37c54f13ad5667474d8b2c5818757e59cf34d77261cd6"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
