name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8bca2f0c1272e91a1070830234263784c3f1f53966d3719f94e46a2257df2ad"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
