name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654cae318721f1a10b1a8ebc4fa89305fb2d95826cfa24f5764007f251f93efb"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
