name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85bdda1e96af4db443e68db6bd4bfdd71342f79d2d24aa95d4e9f4bf120e3c0c"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
