name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "811ef50f000d11520b51588ad4771b78e60ce2e62f0c30103c4d0f9c1c446b25"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
