name = "Diverse North: Revisited"
author = "Ozoku"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "072166ce245066ab0d8372a48594e80d62a5cba0b46985e33c29e1a72b4e0586"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
