name = "Abnormals Delight"
filename = "abnormals_delight-1.16.5-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3442/748/abnormals_delight-1.16.5-1.2.0.jar"
hash-format = "murmur2"
hash = "2225048643"

[update]
[update.curseforge]
file-id = 3442748
project-id = 442719
release-channel = "beta"
