name = "Advanced Peripherals"
filename = "advancedperipherals-1.16.5-0.7.1r.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3435/311/advancedperipherals-1.16.5-0.7.1r.jar"
hash-format = "murmur2"
hash = "4087634131"

[update]
[update.curseforge]
file-id = 3435311
project-id = 431725
release-channel = "beta"
