name = "Alex's Mobs"
filename = "alexsmobs-1.12.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3440/131/alexsmobs-1.12.0.jar"
hash-format = "murmur2"
hash = "2939681888"

[update]
[update.curseforge]
file-id = 3440131
project-id = 426558
release-channel = "beta"
