name = "Apotheosis"
filename = "Apotheosis-1.16.5-4.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3451/418/Apotheosis-1.16.5-4.8.0.jar"
hash-format = "murmur2"
hash = "3774337239"

[update]
[update.curseforge]
file-id = 3451418
project-id = 313970
release-channel = "beta"
