name = "Aquaculture 2"
filename = "Aquaculture-1.16.5-2.1.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3401/886/Aquaculture-1.16.5-2.1.20.jar"
hash-format = "murmur2"
hash = "1393653187"

[update]
[update.curseforge]
file-id = 3401886
project-id = 60028
release-channel = "beta"
