name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.23.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/11/ars_nouveau-1.16.5-1.23.8.jar"
hash-format = "murmur2"
hash = "1464930222"

[update]
[update.curseforge]
file-id = 3459011
project-id = 401955
release-channel = "beta"
