name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.21.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/754/ars_nouveau-1.16.5-1.21.2.jar"
hash-format = "murmur2"
hash = "1839741405"

[update]
[update.curseforge]
file-id = 3424754
project-id = 401955
release-channel = "beta"
