name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.23.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/692/ars_nouveau-1.16.5-1.23.4.jar"
hash-format = "murmur2"
hash = "3677395831"

[update]
[update.curseforge]
file-id = 3453692
project-id = 401955
release-channel = "beta"
