name = "Bamboo Blocks"
filename = "bamboo_blocks-1.16.5-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3416/596/bamboo_blocks-1.16.5-3.0.0.jar"
hash-format = "murmur2"
hash = "2655104770"

[update]
[update.curseforge]
file-id = 3416596
project-id = 348215
release-channel = "beta"
