name = "Battle Towers Lite (Forge)"
filename = "battletowerslite.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3368/58/battletowerslite.jar"
hash-format = "murmur2"
hash = "2880708394"

[update]
[update.curseforge]
file-id = 3368058
project-id = 490893
release-channel = "beta"
