name = "Blood Magic "
filename = "BloodMagic-1.16.4-3.1.1-16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/440/BloodMagic-1.16.4-3.1.1-16.jar"
hash-format = "murmur2"
hash = "3997543782"

[update]
[update.curseforge]
file-id = 3399440
project-id = 224791
release-channel = "beta"
