name = "Botany Pots"
filename = "BotanyPots-1.16.5-7.1.23.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/843/BotanyPots-1.16.5-7.1.23.jar"
hash-format = "murmur2"
hash = "269875015"

[update]
[update.curseforge]
file-id = 3358843
project-id = 353928
release-channel = "beta"
