name = "Caelus API (Forge)"
filename = "caelus-forge-1.16.5-2.1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3403/876/caelus-forge-1.16.5-2.1.3.1.jar"
hash-format = "murmur2"
hash = "2077954968"

[update]
[update.curseforge]
file-id = 3403876
project-id = 308989
release-channel = "beta"
