name = "CaveBiomeAPI [Forge]"
filename = "cavebiomeapi-1.16.5-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3413/613/cavebiomeapi-1.16.5-1.3.1.jar"
hash-format = "murmur2"
hash = "2756858920"

[update]
[update.curseforge]
file-id = 3413613
project-id = 441706
release-channel = "beta"
