name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.16.5-4.0.3.433-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3448/50/CodeChickenLib-1.16.5-4.0.3.433-universal.jar"
hash-format = "murmur2"
hash = "916886514"

[update]
[update.curseforge]
file-id = 3448050
project-id = 242818
release-channel = "beta"
