name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.16.5-4.0.2.429-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3398/96/CodeChickenLib-1.16.5-4.0.2.429-universal.jar"
hash-format = "murmur2"
hash = "694341700"

[update]
[update.curseforge]
file-id = 3398096
project-id = 242818
release-channel = "beta"
