name = "Comfortable Nether"
filename = "ComfortableNether4.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3438/737/ComfortableNether4.9.jar"
hash-format = "murmur2"
hash = "1197904158"

[update]
[update.curseforge]
file-id = 3438737
project-id = 473604
release-channel = "beta"
