name = "Cookielicious"
filename = "cookielicious-1.16.5-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/933/cookielicious-1.16.5-1.4.1.jar"
hash-format = "murmur2"
hash = "3615662928"

[update]
[update.curseforge]
file-id = 3399933
project-id = 409577
release-channel = "beta"
