name = "Create Crafts & Additions"
filename = "createaddition-1.16.5-20210819a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3430/915/createaddition-1.16.5-20210819a.jar"
hash-format = "murmur2"
hash = "3761001772"

[update]
[update.curseforge]
file-id = 3430915
project-id = 439890
release-channel = "beta"
