name = "Create Crafts & Additions"
filename = "createaddition-1.16.5-20210810a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3421/252/createaddition-1.16.5-20210810a.jar"
hash-format = "murmur2"
hash = "933680657"

[update]
[update.curseforge]
file-id = 3421252
project-id = 439890
release-channel = "beta"
