name = "Customizable Elytra"
filename = "customizableelytra-1.16.4-1.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3433/485/customizableelytra-1.16.4-1.5.5.jar"
hash-format = "murmur2"
hash = "107774743"

[update]
[update.curseforge]
file-id = 3433485
project-id = 440047
release-channel = "beta"
