name = "Customizable Elytra"
filename = "customizableelytra-1.16.4-1.5.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3452/65/customizableelytra-1.16.4-1.5.7.jar"
hash-format = "murmur2"
hash = "4153252403"

[update]
[update.curseforge]
file-id = 3452065
project-id = 440047
release-channel = "beta"
