name = "Customizable Elytra"
filename = "customizableelytra-1.16.4-1.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3390/792/customizableelytra-1.16.4-1.5.4.jar"
hash-format = "murmur2"
hash = "2927214904"

[update]
[update.curseforge]
file-id = 3390792
project-id = 440047
release-channel = "beta"
