name = "Discord Integration Forge"
filename = "dcintegration-forge-2.3.2-1.16.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3408/431/dcintegration-forge-2.3.2-1.16.jar"
hash-format = "murmur2"
hash = "1304714571"

[update]
[update.curseforge]
file-id = 3408431
project-id = 324952
release-channel = "beta"
