name = "DeLogger"
filename = "DeLogger-3.0.3-build.19+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/932/DeLogger-3.0.3-build.19+mc1.16.5.jar"
hash-format = "murmur2"
hash = "1924084303"

[update]
[update.curseforge]
file-id = 3443932
project-id = 413477
release-channel = "beta"
