name = "End Remastered"
filename = "endremastered-forge-R4.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3444/367/endremastered-forge-R4.1.1.jar"
hash-format = "murmur2"
hash = "2413580271"

[update]
[update.curseforge]
file-id = 3444367
project-id = 404183
release-channel = "beta"
