name = "Environmental"
filename = "environmental-1.16.5-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3416/597/environmental-1.16.5-1.1.0.jar"
hash-format = "murmur2"
hash = "3627389999"

[update]
[update.curseforge]
file-id = 3416597
project-id = 388992
release-channel = "beta"
