name = "Farmer's Tea"
filename = "farmerstea-1.16.5-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3255/558/farmerstea-1.16.5-1.2.jar"
hash-format = "murmur2"
hash = "1668057744"

[update]
[update.curseforge]
file-id = 3255558
project-id = 450265
release-channel = "beta"
