name = "Farmer's Tea"
filename = "farmerstea-1.16.5-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3438/997/farmerstea-1.16.5-1.3.jar"
hash-format = "murmur2"
hash = "583879567"

[update]
[update.curseforge]
file-id = 3438997
project-id = 450265
release-channel = "beta"
