name = "Farsight: Spyglasses"
filename = "farsight-1.4.0-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/344/farsight-1.4.0-1.16.5.jar"
hash-format = "murmur2"
hash = "1801307075"

[update]
[update.curseforge]
file-id = 3455344
project-id = 496039
release-channel = "beta"
