name = "FramedBlocks"
filename = "FramedBlocks-2.9.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3412/173/FramedBlocks-2.9.3.jar"
hash-format = "murmur2"
hash = "3085615053"

[update]
[update.curseforge]
file-id = 3412173
project-id = 441647
release-channel = "beta"
