name = "FramedBlocks"
filename = "FramedBlocks-2.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/471/FramedBlocks-2.10.0.jar"
hash-format = "murmur2"
hash = "1193117242"

[update]
[update.curseforge]
file-id = 3453471
project-id = 441647
release-channel = "beta"
