name = "FTB Essentials (Forge)"
filename = "ftb-essentials-1605.1.4-build.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/355/ftb-essentials-1605.1.4-build.20.jar"
hash-format = "murmur2"
hash = "3394438896"

[update]
[update.curseforge]
file-id = 3453355
project-id = 410811
release-channel = "beta"
