name = "FTB Teams (Forge)"
filename = "ftb-teams-forge-1605.2.2-build.32.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3460/43/ftb-teams-forge-1605.2.2-build.32.jar"
hash-format = "murmur2"
hash = "1730578673"

[update]
[update.curseforge]
file-id = 3460043
project-id = 404468
release-channel = "beta"
