name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.45.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3428/832/geckolib-forge-1.16.5-3.0.45.jar"
hash-format = "murmur2"
hash = "1153920412"

[update]
[update.curseforge]
file-id = 3428832
project-id = 388172
release-channel = "beta"
