name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.44.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/157/geckolib-forge-1.16.5-3.0.44.jar"
hash-format = "murmur2"
hash = "128733703"

[update]
[update.curseforge]
file-id = 3424157
project-id = 388172
release-channel = "beta"
