name = "Health Overlay"
filename = "HealthOverlay-1.16.5-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3402/106/HealthOverlay-1.16.5-3.0.0.jar"
hash-format = "murmur2"
hash = "2719004978"

[update]
[update.curseforge]
file-id = 3402106
project-id = 368223
release-channel = "beta"
