name = "Health Overlay"
filename = "HealthOverlay-1.16.5-3.0.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3441/946/HealthOverlay-1.16.5-3.0.1.jar"
hash-format = "murmur2"
hash = "253573689"

[update]
[update.curseforge]
file-id = 3441946
project-id = 368223
release-channel = "beta"
