name = "Immersive Posts"
filename = "immersiveposts-1.16.5-4.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/635/immersiveposts-1.16.5-4.2.0.jar"
hash-format = "murmur2"
hash = "2048201531"

[update]
[update.curseforge]
file-id = 3446635
project-id = 314645
release-channel = "beta"
