name = "Industrial Foregoing"
filename = "industrial-foregoing-1.16.5-3.2.14.5-13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3425/275/industrial-foregoing-1.16.5-3.2.14.5-13.jar"
hash-format = "murmur2"
hash = "2420767045"

[update]
[update.curseforge]
file-id = 3425275
project-id = 266515
release-channel = "beta"
