name = "Integrated Dynamics"
filename = "IntegratedDynamics-1.16.5-1.9.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/990/IntegratedDynamics-1.16.5-1.9.4.jar"
hash-format = "murmur2"
hash = "1535507924"

[update]
[update.curseforge]
file-id = 3443990
project-id = 236307
release-channel = "beta"
