name = "Integrated Tunnels"
filename = "IntegratedTunnels-1.16.5-1.8.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3397/378/IntegratedTunnels-1.16.5-1.8.5.jar"
hash-format = "murmur2"
hash = "3513363457"

[update]
[update.curseforge]
file-id = 3397378
project-id = 251389
release-channel = "beta"
