name = "Kotlin for Forge"
filename = "kotlinforforge-1.14.0-obf.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3387/639/kotlinforforge-1.14.0-obf.jar"
hash-format = "murmur2"
hash = "3311063832"

[update]
[update.curseforge]
file-id = 3387639
project-id = 351264
release-channel = "beta"
