name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.17-build.114.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3460/23/kubejs-forge-1605.3.17-build.114.jar"
hash-format = "murmur2"
hash = "3250263196"

[update]
[update.curseforge]
file-id = 3460023
project-id = 238086
release-channel = "beta"
