name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.82.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3425/591/kubejs-forge-1605.3.15-build.82.jar"
hash-format = "murmur2"
hash = "1660700377"

[update]
[update.curseforge]
file-id = 3425591
project-id = 238086
release-channel = "beta"
