name = "Lepton (Forge)"
filename = "lepton-1.16.5-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3392/57/lepton-1.16.5-1.3.1.jar"
hash-format = "murmur2"
hash = "4127223485"

[update]
[update.curseforge]
file-id = 3392057
project-id = 407384
release-channel = "beta"
