name = "Mahou Tsukai"
filename = "mahoutsukai-1.16.5-v1.31.36.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/768/mahoutsukai-1.16.5-v1.31.36.jar"
hash-format = "murmur2"
hash = "1304583766"

[update]
[update.curseforge]
file-id = 3424768
project-id = 342543
release-channel = "beta"
