name = "Mahou Tsukai"
filename = "mahoutsukai-1.16.5-v1.31.40.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3441/408/mahoutsukai-1.16.5-v1.31.40.jar"
hash-format = "murmur2"
hash = "204219500"

[update]
[update.curseforge]
file-id = 3441408
project-id = 342543
release-channel = "beta"
