name = "Occultism"
filename = "occultism-1.16.5-1.11.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3454/554/occultism-1.16.5-1.11.1.jar"
hash-format = "murmur2"
hash = "3164111328"

[update]
[update.curseforge]
file-id = 3454554
project-id = 361026
release-channel = "beta"
