name = "Occultism"
filename = "occultism-1.16.5-1.11.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/531/occultism-1.16.5-1.11.3.jar"
hash-format = "murmur2"
hash = "4129036723"

[update]
[update.curseforge]
file-id = 3456531
project-id = 361026
release-channel = "beta"
