name = "Panorama"
filename = "panorama-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3183/906/panorama-1.1.jar"
hash-format = "murmur2"
hash = "638274713"

[update]
[update.curseforge]
file-id = 3183906
project-id = 440465
release-channel = "beta"
