name = "Paragliders"
filename = "Paraglider-1.16.5-1.3.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/41/Paraglider-1.16.5-1.3.2.1.jar"
hash-format = "murmur2"
hash = "1486304347"

[update]
[update.curseforge]
file-id = 3407041
project-id = 289240
release-channel = "beta"
