name = "Personality"
filename = "personality-1.16.5-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3227/802/personality-1.16.5-1.0.2.jar"
hash-format = "murmur2"
hash = "216447918"

[update]
[update.curseforge]
file-id = 3227802
project-id = 415974
release-channel = "beta"
