name = "Refined Storage Addons"
filename = "refinedstorageaddons-0.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3400/591/refinedstorageaddons-0.7.3.jar"
hash-format = "murmur2"
hash = "212512365"

[update]
[update.curseforge]
file-id = 3400591
project-id = 272302
release-channel = "beta"
