name = "Relics"
filename = "relics-0.2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3427/184/relics-0.2.6.jar"
hash-format = "murmur2"
hash = "1294937825"

[update]
[update.curseforge]
file-id = 3427184
project-id = 445274
release-channel = "beta"
