name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-3.1.3+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/171/repurposed_structures_forge-3.1.3+1.16.5.jar"
hash-format = "murmur2"
hash = "1254186199"

[update]
[update.curseforge]
file-id = 3424171
project-id = 368293
release-channel = "beta"
