name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-3.2.1+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3429/489/repurposed_structures_forge-3.2.1+1.16.5.jar"
hash-format = "murmur2"
hash = "3592689054"

[update]
[update.curseforge]
file-id = 3429489
project-id = 368293
release-channel = "beta"
