name = "RFTools Power"
filename = "rftoolspower-1.16-3.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/276/rftoolspower-1.16-3.0.9.jar"
hash-format = "murmur2"
hash = "257744224"

[update]
[update.curseforge]
file-id = 3380276
project-id = 290209
release-channel = "beta"
