name = "Rhino"
filename = "rhino-forge-1605.1.4-build.57.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3460/19/rhino-forge-1605.1.4-build.57.jar"
hash-format = "murmur2"
hash = "1800567136"

[update]
[update.curseforge]
file-id = 3460019
project-id = 416294
release-channel = "beta"
