name = "RSInfinityBooster"
filename = "RSInfinityBooster-1.16.5-1.0+6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3241/432/RSInfinityBooster-1.16.5-1.0+6.jar"
hash-format = "murmur2"
hash = "3343322362"

[update]
[update.curseforge]
file-id = 3241432
project-id = 446870
release-channel = "beta"
