name = "Selene"
filename = "selene-1.16.5-1.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3435/337/selene-1.16.5-1.6.1.jar"
hash-format = "murmur2"
hash = "2459168813"

[update]
[update.curseforge]
file-id = 3435337
project-id = 499980
release-channel = "beta"
