name = "Selene"
filename = "selene-1.16.5-1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/606/selene-1.16.5-1.7.jar"
hash-format = "murmur2"
hash = "3241725074"

[update]
[update.curseforge]
file-id = 3453606
project-id = 499980
release-channel = "beta"
