name = "Simple Discord Rich Presence"
filename = "SimpleDiscordRichPresence-1.16.4-1.3.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3103/834/SimpleDiscordRichPresence-1.16.4-1.3.5.jar"
hash-format = "murmur2"
hash = "2909395883"

[update]
[update.curseforge]
file-id = 3103834
project-id = 334853
release-channel = "beta"
