name = "Sodium Reforged (Plus Lithium and Phosphor)"
filename = "sodium-forge-2.9.10+rev.ea6353c.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3410/21/sodium-forge-2.9.10+rev.ea6353c.jar"
hash-format = "murmur2"
hash = "2620665428"

[update]
[update.curseforge]
file-id = 3410021
project-id = 491233
release-channel = "beta"

[option]
default = true
description = "Boosts game performance but makes create moving blocks invisible"
optional = true