name = "Supplementaries"
filename = "supplementaries-1.16.5-0.15.2b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/380/supplementaries-1.16.5-0.15.2b.jar"
hash-format = "murmur2"
hash = "2062771020"

[update]
[update.curseforge]
file-id = 3424380
project-id = 412082
release-channel = "beta"
