name = "ToroHealth Damage Indicators"
filename = "torohealth-1.16.4-forge-4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3144/151/torohealth-1.16.4-forge-4.jar"
hash-format = "murmur2"
hash = "4080510057"

[update]
[update.curseforge]
file-id = 3144151
project-id = 245733
release-channel = "beta"
