name = "Travel Anchors"
filename = "TravelAnchors-2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3265/112/TravelAnchors-2.4.jar"
hash-format = "murmur2"
hash = "2377763499"

[update]
[update.curseforge]
file-id = 3265112
project-id = 413234
release-channel = "beta"
