name = "Villager Names"
filename = "villagernames_1.16.5-3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/421/villagernames_1.16.5-3.3.jar"
hash-format = "murmur2"
hash = "2815461398"

[update]
[update.curseforge]
file-id = 3420421
project-id = 345854
release-channel = "beta"
