name = "Xaero's World Map"
filename = "XaerosWorldMap_1.17.0.1_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/618/XaerosWorldMap_1.17.0.1_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "4190410781"

[update]
[update.curseforge]
file-id = 3443618
project-id = 317780
release-channel = "beta"
