name = "XNet Gases"
filename = "XNetGases-1.16.5-2.3.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3435/369/XNetGases-1.16.5-2.3.7.jar"
hash-format = "murmur2"
hash = "3792918243"

[update]
[update.curseforge]
file-id = 3435369
project-id = 383182
release-channel = "beta"
